return {
	binarytree = require("ff.binarytree"),
	empty = require("ff.empty"),
	factorial = require("ff.factorial"),
	fibonacci = require("ff.fibonacci"),
	hashmap = require("ff.hashmap"),
	head = require("ff.head"),
	heap = require("ff.heap"),
	linkedlist = require("ff.linkedlist"),
	max = require("ff.max"),
	memoize = require("ff.memoize"),
	min = require("ff.min"),
	spy = require("ff.spy"),
	stack = require("ff.stack"),
	tail = require("ff.tail"),
	trunc = require("ff.trunc"),
}
